meta:
  title: "Your Meta Title Here"
  description: "Your meta description goes here. It should be concise and descriptive, giving a brief overview of the content of the page."

google_console:
  id: "hj0Sh0iAIET0ex54mn47AlyNo5yEZmXchoMa4gQUceE"
