meta:
  title: "The Perfect Side Table for Every Room!"
  description: "Read my article on Evernote: The Perfect Side Table for Every Room!"

google_console:
  id: "Mp5J3KOT6QOsZ9NFHK4-EH6Igv64ODruu0ZsI9-1nMo"
